-- MySQL Script generated by MySQL Workbench
-- Thu Aug 12 21:55:10 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema biblioteca
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema biblioteca
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `biblioteca` DEFAULT CHARACTER SET utf8 ;
USE `biblioteca` ;

-- -----------------------------------------------------
-- Table `biblioteca`.`tipo_usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `biblioteca`.`tipo_usuario` (
  `idtipo_usuario` INT NOT NULL AUTO_INCREMENT,
  `rol` VARCHAR(45) NOT NULL,
  `estado` BIT NOT NULL,
  PRIMARY KEY (`idtipo_usuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `biblioteca`.`bibliotecas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `biblioteca`.`bibliotecas` (
  `idbibliotecas` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idbibliotecas`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `biblioteca`.`empleados`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `biblioteca`.`empleados` (
  `idEmpleado` INT NOT NULL AUTO_INCREMENT,
  `usuario` VARCHAR(45) NOT NULL,
  `clave` VARCHAR(45) NOT NULL,
  `estado` BIT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `fecha_registro` DATETIME NOT NULL DEFAULT now(),
  `tipo_usuario_idtipo_usuario` INT NOT NULL,
  `bibliotecas_idbibliotecas` INT NOT NULL,
  PRIMARY KEY (`idEmpleado`),
  INDEX `fk_usuarios_tipo_usuario_idx` (`tipo_usuario_idtipo_usuario` ASC) VISIBLE,
  INDEX `fk_empleados_bibliotecas1_idx` (`bibliotecas_idbibliotecas` ASC) VISIBLE,
  CONSTRAINT `fk_usuarios_tipo_usuario`
    FOREIGN KEY (`tipo_usuario_idtipo_usuario`)
    REFERENCES `biblioteca`.`tipo_usuario` (`idtipo_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_empleados_bibliotecas1`
    FOREIGN KEY (`bibliotecas_idbibliotecas`)
    REFERENCES `biblioteca`.`bibliotecas` (`idbibliotecas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `biblioteca`.`Categorias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `biblioteca`.`Categorias` (
  `idCategorias` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idCategorias`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `biblioteca`.`materiales`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `biblioteca`.`materiales` (
  `idMaterial` INT NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(45) NOT NULL,
  `codigo` VARCHAR(45) NOT NULL,
  `autor` VARCHAR(45) NOT NULL,
  `anio` YEAR NOT NULL,
  `Categorias_idCategorias` INT NOT NULL,
  `estado` BIT NOT NULL,
  `bibliotecas_idbibliotecas` INT NOT NULL,
  PRIMARY KEY (`idMaterial`),
  INDEX `fk_materiales_Categorias1_idx` (`Categorias_idCategorias` ASC) VISIBLE,
  INDEX `fk_materiales_bibliotecas1_idx` (`bibliotecas_idbibliotecas` ASC) VISIBLE,
  CONSTRAINT `fk_materiales_Categorias1`
    FOREIGN KEY (`Categorias_idCategorias`)
    REFERENCES `biblioteca`.`Categorias` (`idCategorias`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_materiales_bibliotecas1`
    FOREIGN KEY (`bibliotecas_idbibliotecas`)
    REFERENCES `biblioteca`.`bibliotecas` (`idbibliotecas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `biblioteca`.`autores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `biblioteca`.`autores` (
  `idautores` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idautores`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `biblioteca`.`autores_has_materiales`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `biblioteca`.`autores_has_materiales` (
  `idAutoresMaterial` INT NOT NULL AUTO_INCREMENT,
  `autores_idautores` INT NOT NULL,
  `materiales_idMaterial` INT NOT NULL,
  PRIMARY KEY (`idAutoresMaterial`),
  INDEX `fk_autores_has_materiales_materiales1_idx` (`materiales_idMaterial` ASC) VISIBLE,
  INDEX `fk_autores_has_materiales_autores1_idx` (`autores_idautores` ASC) VISIBLE,
  CONSTRAINT `fk_autores_has_materiales_autores1`
    FOREIGN KEY (`autores_idautores`)
    REFERENCES `biblioteca`.`autores` (`idautores`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_autores_has_materiales_materiales1`
    FOREIGN KEY (`materiales_idMaterial`)
    REFERENCES `biblioteca`.`materiales` (`idMaterial`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
